### ISSUE TITLE
_ 

### ISSUE THREAD

**Issue by EliteNover** [ishaantek/UniverseList#5]
We know you've stolen this website from VitalList, We've got the DMCA involved.

**Comment by EliteNover** [comment]
I advise clicking:
https://github.com/EliteNover/ishaantek

**Comment by BrydenIsNotSmart** [comment]
Just had to leave credits, wouldn't have cared.

**Comment by EliteNover** [comment]
do what he said

**Comment by EliteNover** [comment]
if you delete this i have all the emails with the replies for this issue

**Comment by EliteNover** [comment]
its sending me every message being sent here

**Comment by ishaantek** [comment]
1. I cannot DM you both.
2. Why don't you ask Kyasa more about this. He knows all the information and I'm sure he can tell you guys.

**Comment by EliteNover** [comment]
should have asked bryden

**Comment by BrydenIsNotSmart** [comment]
Kyasa told me to submit a takedown, already asked him. :/

**Comment by EliteNover** [comment]
i think kyasa is playing 2 personas here

**Comment by EliteNover** [comment]
im gonna go kill kyasa rq

**Comment by BrydenIsNotSmart** [comment]
Why can't you dm us?

**Comment by BrydenIsNotSmart** [comment]
Just add credits and I won't care

**Comment by EliteNover** [comment]
true

**Comment by ishaantek** [comment]
1. What?
2. Check README.md
3. The website is literally down and according to the status bot, it is down 94% of the time.
4. Kyasa knows I literally only made this to test some things out.

**Comment by EliteNover** [comment]
1. its a public github
2. am i about to kill kyasa for no reason
3. why would you remove credits for testing
4. dmca very pleased for brydens business

**Comment by BrydenIsNotSmart** [comment]
If you were testing things out why did you change everything from VitalList to Universe list, and remove our credits claiming you made it yourself.

**Comment by ishaantek** [comment]
1. How does it matter since it's literally not being hosted unless localhost doesn't work, and is only being public so some irl friends can see it? If not this repo is supposed to be private as usual.

**Comment by EliteNover** [comment]
it is illegal

**Comment by BrydenIsNotSmart** [comment]
You just now edited the readme to say that, also doesnt has to be on the website not github.

**Comment by ishaantek** [comment]
What's illegal?
I added credits to a repo that's going to be private soon and a site that isn't hosted.

And you guys spammed my email.

**Comment by EliteNover** [comment]
github did, this website will answer all your questions [right here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by ishaantek** [comment]
Was that necessary?

**Comment by EliteNover** [comment]
it was required, anyway this is a real fucked up move

**Comment by EliteNover** [comment]
you were obv tryna hide something you banned bryden from the server

**Comment by BrydenIsNotSmart** [comment]
universe-list.xyz don't look like localhost to me :/ just saying

**Comment by ishaantek** [comment]
Ok so now what? I added credits and I'm making this private again in a few minutes. What else?

**Comment by ishaantek** [comment]
You banned me from your server as well??

**Comment by ishaantek** [comment]
Are you hiding something??

**Comment by BrydenIsNotSmart** [comment]
That was kyasa

**Comment by EliteNover** [comment]
kyasa did it

**Comment by ishaantek** [comment]
Bruh he said he doesn't want drama and I told him to tell Bryden and I'm waiting for a reply.

**Comment by BrydenIsNotSmart** [comment]
![image](https://user-images.githubusercontent.com/67612593/204958531-006a0840-0b4a-434f-be68-8cd9481e4c3f.png)

**Comment by EliteNover** [comment]
his fault, his problem, not mine.

**Comment by ishaantek** [comment]
Why don't we talk in a GC since I'm being spammed? And this is going private in a minute.

**Comment by EliteNover** [comment]
we have attempted to dm you but no answer

**Comment by ishaantek** [comment]
I literally cannot DM you both except Kyasa

**Comment by ishaantek** [comment]
make a gc or something

**Comment by EliteNover** [comment]
i wonder why

**Comment by BrydenIsNotSmart** [comment]
Hi Ishaan's Universe List server, hope you have a good day. (Sorry just saying hi to your server logs, will be going now.)

**Comment by ishaantek** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/70829999/204958967-e82d2471-adce-4b41-9c94-e1fd19b2ffe2.png">

**Comment by BrydenIsNotSmart** [comment]
mhm I know
