### ISSUE TITLE
"Our Team" Avatar Issue

### ISSUE THREAD

**Issue by arceusxx** [ishaantek/UniverseList#91]
hello, the avatar of "Ghostly#1616" is not correctly displayed on the page "Our Team" (https://universe-list.xyz/team) (see screenshot below,)
tried with firefox, opera and chrome, same issue.
![image](https://github.com/ishaantek/UniverseList/assets/96443442/cd9859e8-40cf-40eb-b3c4-6cd99490033c)

**Comment by ishaantek** [comment]
I plan on re-making the whole page to be dynamic.

**Comment by arceusxx** [comment]
lgtm
